name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.ps1"
      - ".editorconfig"
      - "**/*.gitignore"
      - "**/*.gitattributes"
      - "**/*.yml"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # uses GitHub's checkout action to checkout code form the release branch
      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Use Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: |
          npm ci
          npm run build --if-present
          npm test

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
