name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [dev]
    paths-ignore:
      - "**.md"
      - "**.ps1"
      - ".editorconfig"
      - "**/*.gitignore"
      - "**/*.gitattributes"
      - "**/*.yml"
  pull_request:
    branches: [dev, main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # uses GitHub's checkout action to checkout code form the release branch
      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Use Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: react-sandbox/package-lock.json
          cache: "npm"
      - run: |
          npm ci
          npm run build --if-present
          npm test

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
