name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [dev]
    paths-ignore:
      - "**.md"
      - "**.ps1"
      - ".editorconfig"
      - "**/*.gitignore"
      - "**/*.gitattributes"
      - "**/*.yml"
  pull_request:
    branches: [dev, main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # uses GitHub's checkout action to checkout code form the release branch
      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Build and Deploy React app to GitHub Pages
        uses: omkartapale/react-deployment-gh-pages@v1.0.0
