name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [dev]
    paths-ignore:
      - "**.md"
      - "**.ps1"
      - ".editorconfig"
      - "**/*.gitignore"
      - "**/*.gitattributes"
      - "**/*.yml"
  pull_request:
    branches: [dev, main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: NPM Install
      run: |
       cd react-sandbox
       npm install

    - id: build-publish
      uses: bitovi/github-actions-react-to-github-pages@v1.2.4
      with:
        path: build # change to your build folder
        
